name: CI
on:
  pull_request_target:
    types: [labeled]
jobs:
  testing:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test') && github.event.label
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - run: |
          echo "Running! ${{toJSON(github.event.pull_request.labels)}}"