name: CI Tests (Experimental)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  determine_changed:
    name: "Determine changed modules"
    runs-on: ubuntu-22.04
    outputs:
      modules: ${{ steps.changed-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Setup NDK
        run: |
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          ln -sfn $ANDROID_SDK_ROOT/ndk/21.4.7075529 $ANDROID_NDK_ROOT

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - id: changed-modules
        run: |
          git diff --name-only HEAD~1 | xargs printf -- '--changed-git-paths %s\n' | xargs ./gradlew writeChangedProjects --output-file-path=modules.json
          echo ::set-output name=modules::$(cat modules.json)

  unit_tests:
    name: "Unit Tests"
    runs-on: ubuntu-22.04
    needs:
      - determine_changed
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.determine_changed.outputs.modules) }}

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Setup NDK
        run: |
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          ln -sfn $ANDROID_SDK_ROOT/ndk/21.4.7075529 $ANDROID_NDK_ROOT

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Add google-services.json
        env:
          INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.INTEG_TESTS_GOOGLE_SERVICES }}
        run: |
          echo $INTEG_TESTS_GOOGLE_SERVICES | base64 -d > google-services.json

      - name: Unit Tests (${{ matrix.module }})
        env:
          FIREBASE_CI: 1
        run: |
          ./gradlew ${{matrix.module}}:check withErrorProne
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test Results
          path: "**/build/test-results/**/*.xml"

  integ_tests:
    name: "Instrumentation Tests"
    runs-on: ubuntu-22.04
    needs:
      - determine_changed
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.determine_changed.outputs.modules) }}

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Setup NDK
        run: |
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          ln -sfn $ANDROID_SDK_ROOT/ndk/21.4.7075529 $ANDROID_NDK_ROOT

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Add google-services.json
        env:
          INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.INTEG_TESTS_GOOGLE_SERVICES }}
        run: |
          echo $INTEG_TESTS_GOOGLE_SERVICES | base64 -d > google-services.json
      - uses: google/setup-gcloud@v0.6.0
        with:
          service_account_key: GCP_SERVICE_ACCOUNT

      - name: Instrumentation Tests (${{ matrix.module }})
        env:
          FIREBASE_CI: 1
        run: |
          ./gradlew ${{matrix.module}}:deviceCheck withErrorProne

  publish-test-results:
    name: "Publish Tests Results"
    needs:
      - unit_tests
    runs-on: ubuntu-22.04

    permissions:
      checks: write

      # only needed unless run with comment_mode: off
      pull-requests: write

    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"