name: just-a-test
on:
  pull_request:
    branches:
      - 'master'
jobs:
  android_job:
    name: "Hello"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Setup NDK
        run: |
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          ln -sfn $ANDROID_SDK_ROOT/ndk/21.4.7075529 $ANDROID_NDK_ROOT

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
             ${{ runner.os }}-gradle-
      - name: Check Changed
        env:
          FIREBASE_CI: 1
        run: |
          git log --graph --decorate --pretty=oneline --abbrev-commit
          ./gradlew --continue checkChanged withErrorProne