name: just-a-test
on:
  pull_request:
    branches:
      - 'master'
jobs:
  android_job:
    name: "Hello"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: 21.4.7075529

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
             ${{ runner.os }}-gradle-
      - name: Check Changed
        run: |
          ./gradlew -- --continue checkChanged withErrorProne