
name: On PR
on: pull_request_target
jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo '${{ toJSON(github) }}'
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))