name: On PR
on: pull_request_target
jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo '${{ toJSON(github) }}'
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GOOGLE_OSS_BOT_TOKEN }}
          script: |
            const pr_repo = context.payload.pull_request.head.repo.full_name;
            const target_repo = context.payload.repository.full_name;

            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              name: "ok-to-test"
            }).catch( error => {
              if(error.status != 404) throw error;
            })

            if (pr_repo != target_repo) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: '`ok-to-test` label required'
              });
            } else {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                labels: ["ok-to-test"]
              });
            }
            console.log(JSON.stringify(context));